name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
      - run: echo "$(date)"
      - run: echo "$(date --help)"
      - run: echo "$(date %z -0700)"
